#!/usr/bin/env python3

import os
from cryptography.fernet import Fernet

files = []

for file in os.listdir():
    if file == "ransombox.py" or file == "keys.key" or file == "decrypt.py" or file == "encrypt.py":
        continue
    if os.path.isfile(file):
        files.append(file)

with open("keys.key", "rb") as key_file:
    secretkey = key_file.read()

cipher = Fernet(secretkey)

secretphrase = "marigold"

user_phrase = input("Enter the Decrypter key\n")

if user_phrase == secretphrase:
    for file in files:
        with open(file, "rb") as thefile:
            contents = thefile.read()
        try:
            contents_decrypted = cipher.decrypt(contents)
            with open(file, "wb") as thefile:
                thefile.write(contents_decrypted)
            print(f"{file} has been decrypted successfully.")
        except Exception as e:
            print(f"Failed to decrypt {file}: {e}")
else:
    print("Sorry, Wrong key")
